In [3]:
import keras
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D, Dense, Flatten, ZeroPadding2D, Activation
from keras.preprocessing.image import ImageDataGenerator
import h5py
import os
import cv2
import numpy as np

Using TensorFlow backend.


AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

In [3]:
train_data_dir = 'C:/Users/abhis/Pictures/Smoke_Dataset/Train'
valid_data_dir = 'C:/Users/abhis/Pictures/Smoke_Dataset/Valid'

img_width, img_height = 224,224

In [4]:
vgg16_model = keras.applications.vgg16.VGG16(weights='Z:/vgg16_weights_tf_dim_ordering_tf_kernels.h5')

In [5]:
vgg16_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [6]:
model = Sequential()

for layer in vgg16_model.layers[:-1]:
    
    model.add(layer)
    
for layer in model.layers:
    
    layer.trainable = False
    
model.add(Dense(1,activation='sigmoid'))

In [7]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
__________

In [8]:
datagen = ImageDataGenerator(rescale=1./255)

train_generator = datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=16,
        class_mode='binary',
        shuffle='False')

validation_generator = datagen.flow_from_directory(
        valid_data_dir,
        target_size=(img_width, img_height),
        batch_size=10,
        class_mode='binary',
        shuffle='False')

print('complete')

Found 672 images belonging to 2 classes.
Found 119 images belonging to 2 classes.
complete


In [9]:
model.compile(optimizer=keras.optimizers.SGD(lr=1e-4, momentum=0.9), loss='binary_crossentropy', metrics=['accuracy'])

In [10]:
model.fit_generator(
        train_generator,
        steps_per_epoch=672,
        nb_epoch=5,
        validation_data=validation_generator,
        validation_steps=79)

c:\users\abhis\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  
c:\users\abhis\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras_pre..., steps_per_epoch=672, validation_data=<keras_pre..., validation_steps=79, epochs=5)`
  


Epoch 1/5
672/672 [==============================] - 753s 1s/step - loss: 0.3033 - acc: 0.8970 - val_loss: 0.2605 - val_acc: 0.9247
Epoch 2/5
672/672 [==============================] - 692s 1s/step - loss: 0.1858 - acc: 0.9450 - val_loss: 0.2194 - val_acc: 0.9413
Epoch 3/5
672/672 [==============================] - 692s 1s/step - loss: 0.1595 - acc: 0.9507 - val_loss: 0.2183 - val_acc: 0.9133
Epoch 4/5
672/672 [==============================] - 691s 1s/step - loss: 0.1444 - acc: 0.9523 - val_loss: 0.1980 - val_acc: 0.9451
Epoch 5/5
672/672 [==============================] - 691s 1s/step - loss: 0.1341 - acc: 0.9534 - val_loss: 0.1990 - val_acc: 0.9464


In [11]:
model.save_weights('Z:/Smoke_Classifier_weights/Vgg16_trial_2e.h5')

In [12]:
model.load_weights('Z:/Smoke_Classifier_weights/Vgg16_trial_2e.h5')

In [13]:
model.evaluate_generator(validation_generator,steps=79)

[0.1978774035818123, 0.9476372853092764]

# Using Validation Set to Predict (0 = No Smoke,1 = Smoke)

In [14]:
model.predict_generator(validation_generator,steps=79)

array([[8.75194311e-01],
       [1.76520050e-01],
       [9.44605172e-01],
       [9.85115707e-01],
       [1.15809962e-03],
       [1.41148083e-02],
       [1.76315114e-01],
       [9.31177974e-01],
       [2.81218886e-02],
       [1.58794403e-01],
       [9.61698115e-01],
       [9.32467282e-01],
       [1.18603453e-01],
       [9.26356494e-01],
       [1.09710163e-02],
       [9.78888214e-01],
       [3.56841892e-01],
       [9.12374079e-01],
       [1.45475985e-02],
       [4.63241458e-01],
       [9.86754239e-01],
       [3.35919470e-01],
       [7.55082309e-01],
       [1.30202509e-02],
       [9.94653225e-01],
       [2.78606340e-02],
       [5.98237431e-03],
       [9.48260903e-01],
       [8.98090661e-01],
       [9.55593646e-01],
       [2.49817073e-02],
       [9.84917462e-01],
       [3.48007889e-04],
       [3.60945147e-03],
       [9.13636666e-03],
       [2.89002899e-03],
       [8.48188043e-01],
       [4.64223713e-01],
       [6.34291589e-01],
       [9.79567766e-01],


In [15]:
pred_FullSmoke_data_dir = 'Z:/SmokeDataset'

pred_generator = datagen.flow_from_directory(
        pred_FullSmoke_data_dir,
        target_size=(img_width, img_height),
        batch_size=10,
        class_mode=None,
        shuffle='False')

Found 1275 images belonging to 1 classes.


# All the images fed here contain Smoke (0 = No Smoke, 1 = Smoke)

In [16]:
model.predict_generator(pred_generator,steps=10,verbose=1)

10/10 [==============================] - 7s 750ms/step


array([[0.5754446 ],
       [0.8860041 ],
       [0.9476373 ],
       [0.94819444],
       [0.93293935],
       [0.93010443],
       [0.50870126],
       [0.9302495 ],
       [0.91720676],
       [0.8846443 ],
       [0.8771683 ],
       [0.8684512 ],
       [0.90025985],
       [0.6847924 ],
       [0.91055655],
       [0.9183131 ],
       [0.89454925],
       [0.9110535 ],
       [0.9450451 ],
       [0.9338537 ],
       [0.95185125],
       [0.94090366],
       [0.80605245],
       [0.9292747 ],
       [0.19089623],
       [0.9207222 ],
       [0.94325924],
       [0.8891083 ],
       [0.921645  ],
       [0.868181  ],
       [0.9359008 ],
       [0.93706775],
       [0.81813484],
       [0.9372341 ],
       [0.8843674 ],
       [0.9514808 ],
       [0.9390905 ],
       [0.9451777 ],
       [0.87557495],
       [0.7752719 ],
       [0.93825895],
       [0.93494165],
       [0.89503735],
       [0.8841149 ],
       [0.9350856 ],
       [0.9044522 ],
       [0.77517563],
       [0.858

In [17]:
pred_NoSmoke_data_dir='Z:/KidPics'

pred_nsgenerator = datagen.flow_from_directory(
        pred_NoSmoke_data_dir,
        target_size=(img_width, img_height),
        batch_size=10,
        class_mode=None,
        shuffle='False')

Found 10 images belonging to 1 classes.


# All the images fed here does not contain smoke (0 = No Smoke, 1 = Smoke)

In [18]:
model.predict_generator(pred_nsgenerator,steps=1,verbose=1)

1/1 [==============================] - 1s 1s/step


array([[0.01018639],
       [0.00415769],
       [0.00386722],
       [0.00376147],
       [0.00395524],
       [0.00370444],
       [0.00251726],
       [0.00761582],
       [0.01232117],
       [0.00397901]], dtype=float32)